[package]
name = "zkp"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
num-bigint = { version = "0.4", features = ["rand"] }
rand = "0.8.5"
tonic = "0.12.3"

[build-dependencies]
tonic-build = "0.12"
